name: inventory_system
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  curved_labeled_navigation_bar: ^2.0.6
  firebase_auth: ^5.5.1
  firebase_core: ^3.13.0
  firebase_database: ^11.3.4
  firebase_dynamic_links: ^6.1.4
  flutter:
    sdk: flutter
  intl: ^0.20.2
  mobile_scanner: ^6.0.7
 


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
