// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1Hmk0tGLl9vF0X0NoO2uwqc7s8HGR3W0',
    appId: '1:511744715287:web:b044424ca6531b52a24a52',
    messagingSenderId: '511744715287',
    projectId: 'inventoryappdict',
    authDomain: 'inventoryappdict.firebaseapp.com',
    databaseURL: 'https://inventoryappdict-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'inventoryappdict.firebasestorage.app',
    measurementId: 'G-GXWEVDGY1T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKmSIdRaBMEFs8WoF7JjvKfxJS3JtI5mA',
    appId: '1:511744715287:android:f474a179529b40bea24a52',
    messagingSenderId: '511744715287',
    projectId: 'inventoryappdict',
    databaseURL: 'https://inventoryappdict-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'inventoryappdict.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChANOOLaFcFh603VutSvWGz8SGQIKp0Yw',
    appId: '1:511744715287:ios:2d10454f6905d8b8a24a52',
    messagingSenderId: '511744715287',
    projectId: 'inventoryappdict',
    databaseURL: 'https://inventoryappdict-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'inventoryappdict.firebasestorage.app',
    iosBundleId: 'com.example.inventorySystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChANOOLaFcFh603VutSvWGz8SGQIKp0Yw',
    appId: '1:511744715287:ios:2d10454f6905d8b8a24a52',
    messagingSenderId: '511744715287',
    projectId: 'inventoryappdict',
    databaseURL: 'https://inventoryappdict-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'inventoryappdict.firebasestorage.app',
    iosBundleId: 'com.example.inventorySystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1Hmk0tGLl9vF0X0NoO2uwqc7s8HGR3W0',
    appId: '1:511744715287:web:217a9b2c7c6a080aa24a52',
    messagingSenderId: '511744715287',
    projectId: 'inventoryappdict',
    authDomain: 'inventoryappdict.firebaseapp.com',
    databaseURL: 'https://inventoryappdict-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'inventoryappdict.firebasestorage.app',
    measurementId: 'G-5G7BGVQYHX',
  );
}
